import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import react from '@astrojs/react';
import tailwindcss from '@tailwindcss/vite';
import starlightKbd from 'starlight-kbd';
import lunaria from '@lunariajs/starlight';
import lunariaConfig from './lunaria.config.json';

const locales = {
  root: lunariaConfig.defaultLocale,
  ...lunariaConfig.locales.reduce((acc, locale) => {
    // @ts-expect-error Can't add types for accumulator
    acc[locale.lang] = {
      label: locale.label,
      lang: locale.lang,
    };
    return acc;
  }, {}),
};

const routeMiddleware = ['./src/middleware/ignore-fallback.ts'];
const plugins = [
  starlightKbd({
    globalPicker: false,
    types: [{ id: 'linux', label: 'Linux', default: true }],
  }),
];
if (import.meta.env.PROD) {
  routeMiddleware.push('./src/middleware/outdated.ts');
  plugins.push(
    lunaria({
      route: '/localization',
    })
  );
}

const site = 'https://wiki.cachyos.org/';

// https://astro.build/config
export default defineConfig({
  site,
  vite: {
    plugins: [tailwindcss()],
  },
  integrations: [
    react(),
    starlight({
      locales,
      plugins,
      routeMiddleware,
      favicon: '/favicon.png',
      lastUpdated: true,
      customCss: ['./src/tailwind.css'],
      title: 'CachyOS',
      logo: {
        src: '/src/assets/logo.svg',
      },
      editLink: {
        baseUrl: 'https://github.com/cachyos/wiki/edit/next/',
      },
      expressiveCode: {
        themes: ['ayu-dark', 'light-plus'],
      },
      social: [
        {
          icon: 'github',
          label: 'GitHub',
          href: 'https://github.com/cachyos',
        },
        {
          icon: 'twitter',
          label: 'Twitter',
          href: 'https://twitter.com/cachyos',
        },
        {
          icon: 'discord',
          label: 'Discord',
          href: 'https://discord.gg/cachyos-862292009423470592',
        },
        {
          icon: 'mastodon',
          label: 'Mastodon',
          href: 'https://fosstodon.org/@CachyOS',
        },
      ],
      head: [
        {
          tag: 'meta',
          attrs: {
            property: 'og:image',
            content: site + 'og.jpg?v=1',
          },
        },
        {
          tag: 'meta',
          attrs: {
            property: 'twitter:image',
            content: site + 'og.jpg?v=1',
          },
        },
      ],
      sidebar: [
        {
          label: 'Getting Started',
          translations: {
            cs: 'Začínáme',
            de: 'Erste Schritte',
            el: 'Εισαγωγή',
            es: 'Empezando',
            fr: 'Bien Débuter',
            ja: 'はじめに',
            pl: 'Zaczynamy',
            ru: 'Начало работы',
            sk: 'Začíname',
            pt: 'Introdução',
            bg: 'Първи стъпки',
          },
          items: [
            {
              label: 'How to navigate through the wiki',
              translations: {
                cs: 'Jak se orientovat v wiki',
                de: 'Wie man im Wiki navigiert',
                el: 'Πλοήγηση στο wiki',
                es: 'Cómo navegar por la wiki',
                fr: 'Bien utiliser le wiki',
                ja: 'Wiki の使い方',
                pl: 'Jak poruszać się po wiki',
                ru: 'Как ориентироваться в вики',
                sk: 'Ako sa orientovať v wiki',
                pt: 'Como navegar na wiki',
                bg: 'Как да се ориентирате в уикито',
              },
              link: 'cachyos_basic/navigation-guide',
            },
            {
              label: 'Why CachyOS?',
              translations: {
                cs: 'Proč CachyOS?',
                de: 'Warum CachyOS?',
                el: 'Γιατί να επιλέξω το CachyOS;',
                es: '¿Por qué CachyOS?',
                fr: 'Pourquoi CachyOS',
                ja: 'CachyOS を選ぶ理由',
                pl: 'Dlaczego CachyOS?',
                ru: 'Почему CachyOS?',
                sk: 'Prečo CachyOS?',
                pt: 'Porquê o CachyOS?',
                bg: 'Защо CachyOS?',
              },
              link: 'cachyos_basic/why_cachyos',
            },
            {
              label: 'Download & Verify ISO',
              translations: {
                cs: 'Stažení a ověření ISO',
                de: 'ISO herunterladen & verifizieren',
                el: 'Λήψη και επαλήθευση ISO',
                es: 'Descargar y verificar ISO',
                fr: 'Télécharger et vérifier l’ISO',
                ja: 'ISO のダウンロードと検証',
                pl: 'Pobierz i zweryfikuj ISO',
                ru: 'Скачать и проверить ISO',
                sk: 'Stiahnutie a overenie ISO',
                pt: 'Descarregar e Verificar ISO',
                bg: 'Изтегляне и проверка на ISO',
              },
              link: 'cachyos_basic/download',
            },
            {
              label: 'ISO Changelogs',
              autogenerate: { directory: 'cachyos_basic/changelogs' },
              translations: {
                el: 'Αρχεία αλλαγών ISO',
                ja: 'ISO 更新ログ',
		ru: 'Журналы изменений ISO',
                bg: 'Списък на промените',
              },
            },
            {
              label: 'FAQ & Troubleshooting',
              translations: {
                cs: 'FAQ a řešení problémů',
                de: 'FAQ & Fehlerbehebung',
                el: 'Συχνές ερωτήσεις και επίλυση προβλημάτων',
                es: 'FAQ y solución de problemas',
                fr: 'FAQ & Guide de dépannage',
                ja: 'FAQ とトラブルシューティング',
                pl: 'FAQ i rozwiązywanie problemów',
                ru: 'FAQ и устранение неполадок',
                sk: 'FAQ a riešenie problémov',
                pt: 'Perguntas Frequentes e Resolução de Problemas',
                bg: 'FAQ и отстраняване на проблеми',
              },
              link: 'cachyos_basic/faq',
            },
          ],
        },
        {
          label: 'Installation',
          translations: {
            cs: 'Instalace',
            de: 'Installation',
            el: 'Εγκατάσταση',
            es: 'Instalación',
            fr: 'Installation',
            ja: 'インストール',
            pl: 'Instalacja',
            ru: 'Установка',
            sk: 'Inštalácia',
            pt: 'Instalação',
            bg: 'Инсталация',
          },
          items: [
            {
              label: 'Requirements & USB Preparation',
              translations: {
                cs: 'Požadavky a příprava USB',
                de: 'Anforderungen & USB-Vorbereitung',
                el: 'Απαιτήσεις και προετοιμασία USB',
                es: 'Requisitos y preparación de USB',
                fr: 'Exigences & Préinstallation',
                ja: '動作要件と USB の準備',
                pl: 'Wymagania i przygotowanie USB',
                ru: 'Требования и подготовка USB',
                sk: 'Požiadavky a príprava USB',
                pt: 'Requisitos e Preparação do USB',
                bg: 'Изисквания и подготовка на USB',
              },
              link: 'installation/installation_prepare',
            },
            {
              label: 'Boot Managers',
              translations: {
                cs: 'Správci zavádění',
                de: 'Boot-Manager',
                el: 'Διαχειριστές εκκίνησης',
                es: 'Gestores de arranque',
                fr: "Gestionnaire d'amorçage",
                ja: 'ブートマネージャー',
                pl: 'Boot menedżer',
                ru: 'Boot менеджер',
                sk: 'Boot manažéry',
                pt: 'Gestores de Arranque',
                bg: 'Boot мениджъри',
              },
              link: 'installation/boot_managers',
            },
            {
              label: 'Filesystem',
              translations: {
                cs: 'Souborový systém',
                de: 'Dateisystem',
                el: 'Σύστημα αρχείων',
                es: 'Sistema de archivos',
                fr: 'Système de fichier',
                ja: 'ファイルシステム',
                pl: 'System plików',
                ru: 'Файловая система',
                sk: 'Súborový systém',
                pt: 'Sistema de Ficheiros',
                bg: 'Файлова система',
              },
              link: 'installation/filesystem',
            },
            {
              label: 'Desktop Environments',
              translations: {
                cs: 'Desktop prostředí',
                de: 'Desktop-Umgebungen',
                el: 'Περιβάλλοντα επιφάνειας εργασίας',
                es: 'Entornos de escritorio',
                fr: 'Environnements de bureau',
                ja: 'デスクトップ環境',
                pl: 'Środowiska graficzne',
                ru: 'Окружения рабочего стола',
                sk: 'Desktopové prostredia',
                pt: 'Ambientes de Trabalho',
                bg: 'Графични среди',
              },
              link: 'installation/desktop_environments',
            },
            {
              label: 'Guides',
              translations: {
                cs: 'Průvodce',
                de: 'Anleitungen',
                el: 'Οδηγοί',
                es: 'Guías',
                fr: 'Guides',
                ja: 'ガイド',
                pl: 'Przewodniki',
                ru: 'Руководства',
                sk: 'Príručky',
                pt: 'Guias',
                bg: 'Ръководства',
              },
              items: [
                {
                  label: 'Desktop Edition',
                  translations: {
                    cs: 'Desktop verze',
                    de: 'Desktop Edition',
                    el: 'Έκδοση Desktop',
                    es: 'Edición de escritorio',
                    fr: 'Edition Desktop',
                    ja: 'デスクトップ版',
                    pl: 'Wersja desktop',
                    ru: 'Десктоп версия',
                    sk: 'Desktop verzia',
                    pt: 'Edição Desktop',
                    bg: 'Desktop версия',
                  },
                  link: 'installation/installation_on_root',
                },
                {
                  label: 'Handheld Edition',
                  translations: {
                    cs: 'Handheld verze',
                    de: 'Handheld Edition',
                    el: 'Έκδοση Handheld',
                    es: 'Edición para dispositivos portátiles',
                    fr: 'Edition Handheld',
                    ja: 'ハンドヘルド版',
                    pl: 'Wersja handheld',
                    ru: 'Портативная версия',
                    sk: 'Handheld verzia',
                    pt: 'Edição Handheld',
                    bg: 'Handheld версия',
                  },
                  link: 'installation/installation_handheld',
                },
                {
                  label: 'T2 MacBook',
                  link: 'installation/installation_t2macbook',
                },
              ],
            },
          ],
        },
        {
          label: 'CachyOS Features',
          translations: {
            cs: 'Funkce CachyOS',
            de: 'CachyOS Funktionen',
            el: 'Λειτουργίες του CachyOS',
            es: 'Funciones de CachyOS',
            fr: 'Fonctionnalités de CachyOS',
            ja: 'CachyOS の機能',
            pl: 'Funkcje CachyOS',
            ru: 'Возможности CachyOS',
            sk: 'Funkcie CachyOS',
            pt: 'Funcionalidades do CachyOS',
            bg: 'Функции на CachyOS',
          },
          items: [
            {
              label: 'CachyOS chroot Helper (cachy-chroot)',
              link: 'features/cachy_chroot',
              translations: {
                cs: 'Pomůcka pro chroot CachyOS (cachy-chroot)',
                de: 'CachyOS chroot-Helfer (cachy-chroot)',
                el: 'Βοηθός chroot του CachyOS (cachy-chroot)',
                es: 'CachyOS chroot asistente (cachy-chroot)',
                fr: 'CachyOS chroot assistant (cachy-chroot)',
                ja: 'CachyOS chroot ヘルパー (cachy-chroot)',
                pl: 'CachyOS chroot menedżer (cachy-chroot)',
                ru: 'CachyOS chroot помощник (cachy-chroot)',
                sk: 'Pomôcka pre chroot CachyOS (cachy-chroot)',
                pt: 'Assistente chroot do CachyOS (cachy-chroot)',
                bg: 'CachyOS chroot Помощник (cachy-chroot)',
              },
            },
            {
              label: 'CachyOS Hardware Detection (chwd)',
              autogenerate: { directory: 'features/chwd' },
              translations: {
                cs: 'Detekce hardwaru CachyOS (chwd)',
                de: 'CachyOS Hardware-Erkennung (chwd)',
                el: 'Εντοπισμός υλικού στο CachyOS (chwd)',
                es: 'CachyOS detección de hardware (chwd)',
                fr: 'CachyOS Détection de Matériel (chwd)',
                ja: 'CachyOS ハードウェア検出 (chwd)',
                pl: 'CachyOS Wykrywanie sprzętu (chwd)',
                ru: 'CachyOS Обнаружение оборудования (chwd)',
                sk: 'Detekcia hardvéru CachyOS (chwd)',
                pt: 'Deteção de Hardware do CachyOS (chwd)',
                bg: 'CachyOS откриване на хардуер (chwd)',
              },
            },
            {
              label: 'CachyOS Kernel',
              translations: {
                cs: 'Jádro CachyOS',
                de: 'CachyOS-Kernel',
                el: 'Πυρήνας CachyOS',
                es: 'Kernel CachyOS',
                fr: 'Noyau CachyOS',
                ja: 'CachyOS カーネル',
                pl: 'Jądro CachyOS',
                ru: 'Ядро CachyOS',
                sk: 'Jadro CachyOS',
                pt: 'Kernel do CachyOS',
                bg: 'Ядро на CachyOS',
              },
              link: 'features/kernel',
            },
            {
              label: 'Kernel Manager',
              translations: {
                cs: 'Správce jader',
                de: 'Kernel-Manager',
                el: 'Διαχειριστής πυρήνα',
                es: 'Gestor de núcleos',
                fr: 'Gestion de Noyaux',
                ja: 'カーネルマネージャー',
                pl: 'Menedżer jądra',
                ru: 'Менеджер ядер',
                sk: 'Správca jadra',
                pt: 'Gestor de Kernel',
                bg: 'Мениджър на ядра',
              },
              link: 'features/kernel_manager',
            },
            {
              label: 'CachyOS Settings',
              translations: {
                cs: 'Nastavení CachyOS',
                de: 'CachyOS-Einstellungen',
                el: 'Ρυθμίσεις του CachyOS',
                es: 'Ajustes de CachyOS',
                fr: 'Paramètres de CachyOS',
                ja: 'CachyOS 設定',
                pl: 'Ustawienia CachyOS',
                ru: 'Настройки CachyOS',
                sk: 'Nastavenia CachyOS',
                pt: 'Definições do CachyOS',
                bg: 'Настройки на CachyOS',
              },
              link: 'features/cachyos_settings',
            },
            {
              label: 'Optimized Repositories',
              translations: {
                cs: 'Optimalizované repozitáře',
                de: 'Optimierte Repositories',
                el: 'Βελτιστοποιημένα αποθετήρια',
                es: 'Repositorios optimizados',
                fr: 'Dépôts Optimisés',
                ja: '最適化リポジトリ',
                pl: 'Zoptymalizowane repozytoria',
                ru: 'Оптимизированные репозитории',
                sk: 'Optimalizované repozitáre',
                pt: 'Repositórios Otimizados',
                bg: 'Оптимизирани репоситорита',
              },
              link: 'features/optimized_repos',
            },
          ],
        },
        {
          label: 'Configuration',
          translations: {
            cs: 'Nastavení',
            de: 'Konfiguration',
            el: 'Διαμόρφωση',
            es: 'Configuración',
            fr: 'Configuration',
            ja: '設定',
            pl: 'Konfiguracja',
            ru: 'Конфигурация',
            sk: 'Konfigurácia',
            pt: 'Configuração',
            bg: 'Конфигурация',
          },
          items: [
            {
              label: 'Secure Boot Setup',
              translations: {
                cs: 'Nastavení zabezpečeného spouštění',
                de: 'Secure Boot-Einrichtung',
                el: 'Ρύθμιση του Secure Boot',
                es: 'Configuración de arranque seguro',
                fr: 'Configuration de Secure Boot',
                ja: 'セキュアブートの設定',
                pl: 'Konfiguracja Secure Boot',
                ru: 'Настройка Secure Boot',
                sk: 'Nastavenie zabezpečeného spúšťania',
                pt: 'Configuração do Secure Boot',
                bg: 'Настройка на Secure Boot',
              },
              link: 'configuration/secure_boot_setup',
            },
            {
              label: 'Post Install Recommendations',
              translations: {
                cs: 'Návrhy po instalaci',
                de: 'Post-Install-Raten',
                el: 'Προτάσεις μετά την εγκατάσταση',
                es: 'Recomendaciones post-instalación',
                fr: 'Recommendations Post-Installation',
                ja: 'インストール後の推奨設定',
                pl: 'Rekomendacje po instalacji',
                ru: 'Рекомендации после установки',
                sk: 'Rekomendácie po inštalácii',
                pt: 'Recomendações Pós-Instalação',
                bg: 'Препоръки след инсталация',
              },
              link: 'configuration/post_install_setup',
            },
            {
              label: 'Boot Manager Configuration',
              translations: {
                cs: 'Konfigurace správce spouštění',
                de: 'Boot-Manager-Konfiguration',
                el: 'Ρύθμιση διαχειριστή εκκίνησης',
                es: 'Configuración del gestor de arranque',
                fr: "Configuration du gestionnaire d'amorçage",
                ja: 'ブートマネージャーの設定',
                pl: 'Konfiguracja Boot Managera',
                ru: 'Конфигурация Boot менеджера',
                sk: 'Konfigurácia Boot manažéra',
                pt: 'Configuração do Gestor de Arranque',
                bg: 'Конфигурация на мениджъра за зареждане',
              },
              link: 'configuration/boot_manager_configuration',
            },
            {
              label: 'Btrfs Snapshots',
              translations: {
                cs: 'Btrfs snapshoty',
                de: 'Btrfs-Snapshots',
                el: 'Στιγμιότυπα Btrfs',
                es: 'Snapshots de Btrfs',
                fr: 'Snapshots Btrfs',
                ja: 'Btrfs スナップショット',
                pl: 'Snapshoty Btrfs',
                ru: 'Снимки Btrfs',
                sk: 'Btrfs snapshoty',
                pt: 'Snapshots Btrfs',
                bg: 'Btrfs snapshots',
              },
              link: 'configuration/btrfs_snapshots',
            },
            {
              label: 'Dual GPU',
              translations: {
                cs: 'Dvojité GPU',
                de: 'Doppelte GPU',
                el: 'Διπλή GPU',
                es: 'GPU dual',
                fr: 'Double GPU',
                ja: 'デュアル GPU',
                pl: 'Dwie GPU',
                ru: 'Двойная GPU',
                sk: 'Dvojité GPU',
                pt: 'GPU Dupla',
                bg: 'Две графични карти',
              },
              link: 'configuration/dual_gpu',
            },
            {
              label: 'Gaming',
              link: 'configuration/gaming',
              translations: {
                cs: 'Hraní her',
                de: 'Gaming',
                el: 'Παιχνίδια',
                es: 'Juegos',
                fr: 'Gaming',
                ja: 'ゲーム',
                pl: 'Gry',
                ru: 'Игры',
                sk: 'Hranie hier',
                pt: 'Jogos / Gaming',
                bg: 'Гейминг',
              },
            },
            {
              label: 'General System Tweaks',
              translations: {
                cs: 'Obecné úpravy systému',
                de: 'Allgemeine Systemanpassungen',
                el: 'Γενικές προσαρμογές συστήματος',
                es: 'Ajustes generales del sistema',
                fr: 'Ajustements généraux du système',
                ja: 'システムの全般的なチューニング',
                pl: 'Ogólne poprawki systemowe',
                ru: 'Общие настройки системы',
                sk: 'Všeobecné systémové úpravy',
                pt: 'Ajustes Gerais do Sistema',
                bg: 'Общи системни настройки',
              },
              link: 'configuration/general_system_tweaks',
            },
            {
              label: 'sched-ext Tutorial',
              translations: {
                cs: 'sched-ext Tutoriál',
                de: 'sched-ext Anleitung',
                el: 'Οδηγός για το sched-ext',
                es: 'Tutorial de sched-ext',
                fr: 'Tutorial sur sched-ext',
                ja: 'sched-ext チュートリアル',
                pl: 'sched-ext Poradnik',
                ru: 'Руководство по sched-ext',
                sk: 'sched-ext návod',
                pt: 'Tutorial do sched-ext',
                bg: 'Ръководство за sched-ext',
              },
              link: 'configuration/sched-ext',
            },
            {
              label: 'Automounting Additional Drives',
              translations: {
                cs: 'Automatické připojování dalších disků',
                de: 'Automatisches Einhängen zusätzlicher Laufwerke',
                el: 'Αυτόματη προσάρτηση πρόσθετων μονάδων',
                es: 'Montaje automático de unidades adicionales',
                fr: 'Montage automatique de disques supplémentaires',
                ja: '追加ドライブの自動マウント',
                pl: 'Automatyczne montowanie dodatkowych dysków',
                ru: 'Автоматическое монтирование дополнительных дисков',
                sk: 'Automatické pripájanie ďalších diskov',
                pt: 'Montagem Automática de Unidades Adicionais',
                bg: 'Автомонтиране на допълнителни дискове',
              },
              link: 'configuration/automount_with_fstab',
            },
            {
              label: 'Enabling Hardware Acceleration in Google Chrome',
              translations: {
                cs: 'Povolení hardwarové akcelerace v Google Chrome',
                de: 'Hardware-Beschleunigung in Google Chrome aktivieren',
                el: 'Ενεργοποίηση επιτάχυνσης υλικού στο Google Chrome',
                es: 'Habilitar la aceleración por hardware en Google Chrome',
                fr: "Activer l'accélération matérielle sur Google Chrome",
                ja: 'Google Chrome でハードウェアアクセラレーションを有効にする',
                pl: 'Włączanie akceleracji sprzętowej w Google Chrome',
                ru: 'Включение аппаратного ускорения в Google Chrome',
                sk: 'Povolenie hardvérovej akcelerácie v Google Chrome',
                pt: 'Ativar Aceleração de Hardware no Google Chrome',
                bg: 'Включване на хардуерно ускорение в Google Chrome',
              },
              link: 'configuration/enabling_hardware_acceleration_in_google_chrome',
            },
            {
              label: 'Desktop Environments',
              autogenerate: { directory: 'configuration/desktop_environments' },
              translations: {
                el: 'Επιφάνειες εργασίας',
                ja: 'デスクトップ環境',
                ru: 'Окружения рабочего стола',
                bg: 'Графични среди',
              },
            },
          ],
        },
        {
          label: 'Virtualization',
          translations: {
            el: 'Εικονικοποίηση',
            ja: '仮想化',
            pt: 'Virtualização',
            ru: 'Виртуализация',
            bg: 'Виртуализация',
          },
          items: [
            {
              label: 'QEMU and VMM Setup',
              translations: {
                el: 'Ρύθμιση των QEMU και VMM',
                ja: 'QEMU と VMM のセットアップ',
                pt: 'Configuração do QEMU e VMM',
                ru: 'Настройка QEMU и VMM',
                bg: 'Настройка на QEMU и VMM',
              },
              link: 'virtualization/qemu_and_vmm_setup',
            },
            {
              label: 'QEMU User Session',
              translations: {
                el: 'Συνεδρία χρήστη QEMU',
                ja: 'QEMU ユーザーセッション',
                pt: 'Sessão de Utilizador QEMU',
                ru: 'Пользовательская сессия QEMU',
                bg: 'Потребителска сесия на QEMU',
              },
              link: 'virtualization/qemu_user_session',
            },
            {
              label: 'EGL Headless',
              translations: {
                el: 'EGL Headless',
                ja: 'EGL ヘッドレス',
                pt: 'EGL Headless',
                ru: 'Безэкранный EGL',
                bg: 'EGL Headless',
              },
              link: 'virtualization/egl_headless',
            },
            {
              label: 'Virtio-Venus',
              translations: {
                el: 'Virtio-Venus',
                ja: 'Virtio-Venus',
                pt: 'Virtio-Venus',
                ru: 'Virtio-Venus',
                bg: 'Virtio-Venus',
              },
              link: 'virtualization/virtio-venus',
            },
          ],
        },
        {
          label: 'Support',
          translations: {
            cs: 'Podpora',
            de: 'Unterstützung',
            el: 'Υποστήριξη',
            es: 'Soporte',
            fr: 'Support',
            ja: 'サポート',
            pl: 'Wsparcie',
            ru: 'Поддержка',
            sk: 'Podpora',
            pt: 'Suporte',
            bg: 'Поддръжка',
          },
          items: [
            {
              label: 'Donation',
              translations: {
                cs: 'Dobrovolné příspěvky',
                de: 'Spende',
                el: 'Δωρεές',
                es: 'Donación',
                fr: 'Donations',
                ja: '寄付',
                pl: 'Darowizna',
                ru: 'Пожертвования',
                sk: 'Darcovstvo',
                pt: 'Doações',
                bg: 'Подкрепи ни',
              },
              link: 'support/donation',
            },
            {
              label: 'Social',
              translations: {
                cs: 'Sociální sítě',
                de: 'Soziale Medien',
                el: 'Κοινωνικά δίκτυα',
                es: 'Redes sociales',
                fr: 'Réseaux Sociaux',
                ja: 'コミュニティ',
                pl: 'Media społecznościowe',
                ru: 'Социальные сети',
                sk: 'Sociálne siete',
                pt: 'Redes Sociais',
                bg: 'Социални мрежи',
              },
              link: 'support/social',
            },
          ],
        },
        {
          label: 'Policy',
          translations: {
            cs: 'Podmínky',
            de: 'Regeln',
            el: 'Πολιτικές',
            es: 'Política',
            fr: 'Politique',
            ja: 'ポリシー',
            pl: 'Zasady',
            ru: 'Правила',
            sk: 'Politika',
            pt: 'Políticas',
            bg: 'Политики',
          },
          items: [
            {
              label: 'Community Rules',
              translations: {
                cs: 'Pravidla komunity',
                de: 'Gemeinschaftsregeln',
                el: 'Κανόνες κοινότητας',
                es: 'Reglas de la comunidad',
                fr: 'Règles de la communauté',
                ja: 'コミュニティルール',
                pl: 'Zasady społeczności',
                ru: 'Правила сообщества',
                sk: 'Pravidlá komunity',
                pt: 'Regras da Comunidade',
                bg: 'Правила на общността',
              },
              link: 'policy/community-rules',
            },
            {
              label: 'Code of Conduct',
              translations: {
                cs: 'Kodex chování',
                de: 'Verhaltenskodex',
                el: 'Κώδικας δεοντολογίας',
                es: 'Código de conducta',
                fr: 'Code de Conduite',
                ja: '行動規範',
                pl: 'Kodeks postępowania',
                ru: 'Кодекс поведения',
                sk: 'Kódex správania',
                pt: 'Código de Conduta',
                bg: 'Кодекс за Поведение',
              },
              link: 'policy/code_of_conduct',
            },
            {
              label: 'Terms of Service',
              translations: {
                cs: 'Obchodní podmínky',
                de: 'Nutzungsbedingungen',
                el: 'Όροι χρήσης',
                es: 'Términos de servicio',
                fr: "Conditions générales d'utilisation",
                ja: '利用規約',
                pl: 'Warunki korzystania z usługi',
                ru: 'Условия обслуживания',
                sk: 'Podmienky služby',
                pt: 'Termos de Serviço',
                bg: 'Условия за ползване',
              },
              link: 'policy/terms_of_service',
            },
            {
              label: 'Privacy Policy',
              translations: {
                cs: 'Zásady ochrany osobních údajů',
                de: 'Datenschutz-Bestimmungen',
                el: 'Πολιτική απορρήτου',
                es: 'Política de privacidad',
                fr: 'Vie Privée',
                ja: 'プライバシーポリシー',
                pl: 'Polityka prywatności',
                ru: 'Политика конфиденциальности',
                sk: 'Zásady ochrany osobných údajov',
                pt: 'Política de Privacidade',
                bg: 'Политика за поверителност',
              },
              link: 'policy/privacy_policy',
            },
            {
              label: 'Repository Policy',
              translations: {
                cs: 'Repozitářní politika',
                de: 'Repository Regeln',
                el: 'Πολιτική αποθετηρίων',
                es: 'Política de repositorios',
                fr: 'Politique des dépôts',
                ja: 'リポジトリポリシー',
                pl: 'Polityka repozytoriów',
                ru: 'Правила репозитория',
                sk: 'Politika repozitárov',
                pt: 'Política de Repositórios',
                bg: 'Политика за репоситорита',
              },
              link: 'policy/repository_policy',
            },
          ],
        },
      ],
    }),
  ],
});
